using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Inshiminator.Generators;

[Generator]
public class ClockGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("IClock.g.cs", SourceText.From(GenerateInterface(), Encoding.UTF8));
            ctx.AddSource("SystemClock.g.cs", SourceText.From(GenerateImplementation(), Encoding.UTF8));
            ctx.AddSource("ClockServiceCollectionExtensions.g.cs", SourceText.From(GenerateDiExtensions(), Encoding.UTF8));
        });
    }

    private static string GenerateDiExtensions()
    {
        return @"// <auto-generated/>
using Microsoft.Extensions.DependencyInjection;
using Inshiminator.Generated;

namespace Inshiminator.Generated;

public static class ClockServiceCollectionExtensions
{
    public static IServiceCollection AddInshiminatorClock(this IServiceCollection services)
    {
        services.AddSingleton<IClock, SystemClock>();
        return services;
    }
}
";
    }

    private static string GenerateInterface()
    {
        return @"// <auto-generated/>
using System;

namespace Inshiminator.Generated;

public interface IClock
{
    DateTimeOffset UtcNow { get; }
    DateTimeOffset Now { get; }
}
";
    }

    private static string GenerateImplementation()
    {
        return @"// <auto-generated/>
using System;

namespace Inshiminator.Generated;

public sealed class SystemClock : IClock
{
    public DateTimeOffset UtcNow => DateTimeOffset.UtcNow;
    public DateTimeOffset Now => DateTimeOffset.Now;
}
";
    }
}
