using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Inshiminator.Generators;

[Generator]
public class GuidGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("IGuidGenerator.g.cs", SourceText.From(GenerateInterface(), Encoding.UTF8));
            ctx.AddSource("SystemGuidGenerator.g.cs", SourceText.From(GenerateImplementation(), Encoding.UTF8));
            ctx.AddSource("GuidServiceCollectionExtensions.g.cs", SourceText.From(GenerateDiExtensions(), Encoding.UTF8));
        });
    }

    private static string GenerateDiExtensions()
    {
        return @"// <auto-generated/>
using Microsoft.Extensions.DependencyInjection;
using Inshiminator.Generated;

namespace Inshiminator.Generated;

public static class GuidServiceCollectionExtensions
{
    public static IServiceCollection AddInshiminatorGuidGenerator(this IServiceCollection services)
    {
        services.AddSingleton<IGuidGenerator, SystemGuidGenerator>();
        return services;
    }
}
";
    }

    private static string GenerateInterface()
    {
        return @"// <auto-generated/>
using System;

namespace Inshiminator.Generated;

public interface IGuidGenerator
{
    Guid NewGuid();
}
";
    }

    private static string GenerateImplementation()
    {
        return @"// <auto-generated/>
using System;

namespace Inshiminator.Generated;

public sealed class SystemGuidGenerator : IGuidGenerator
{
    public Guid NewGuid() => Guid.NewGuid();
}
";
    }
}
